# Generated by Django 4.2.7 on 2024-02-13 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gemeinde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Leistungsanbietende',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('taetigkeit', models.TextField(blank=True)),
                ('beschreibung', models.TextField(blank=True)),
                ('leistung', models.BooleanField(default=False)),
                ('gemeinde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kantonale_leistungen.gemeinde')),
            ],
        ),
    ]
