# Generated by Django 4.2.7 on 2024-02-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kantonale_leistungen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leistungsanbietende',
            name='gemeinde',
        ),
        migrations.AddField(
            model_name='leistungsanbietende',
            name='gemeinden',
            field=models.ManyToManyField(related_name='leistungsanbietende', to='kantonale_leistungen.gemeinde'),
        ),
        migrations.AddField(
            model_name='leistungsanbietende',
            name='internetlink',
            field=models.URLField(blank=True),
        ),
    ]
