# Generated by Django 4.2.7 on 2024-02-14 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kantonale_leistungen', '0002_remove_leistungsanbietende_gemeinde_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leistungsanbietende',
            old_name='gemeinden',
            new_name='gemeinde',
        ),
    ]
